### ISSUE TITLE
Files from Tin Can Bay

### ISSUE THREAD

**Issue by YvonneP** [QutBioacoustics/QutBioacoustics.github.io#22]
Hi Anthony,

On the SD card there are two files in the folder labelled "Data Tin Can Bay",  could you please analyse this data using course and fine grained indices ie. 60 seconds and 5 seconds.  

Thanks
Yvonne

**Comment by atruskie** [comment]
Closing in favour of https://github.com/QutBioacoustics/Ecoacoustics/issues/26

This is a public issue tracker for _our website_. Analysis jobs should not be listed here.
