### ISSUE TITLE
Add Mark's thesis experiment revival post

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/QutBioacoustics.github.io#36]

**Comment by cofiem** [comment]
Part 1 done! Part 2 and pull request for part 1 some time this week.

**Comment by atruskie** [comment]
update? :smile:

**Comment by cofiem** [comment]
Ah, yes, part 2..... I will do that.

**Comment by cofiem** [comment]
Well, I didn't end up doing part 2. What was part 2? Something about my prototypes?

**Comment by atruskie** [comment]
>In a subsequent post I will go through the prototypes I created and how they were tested.

[First](http://research.ecosounds.org/2015/09/28/Interfaces-for-Analysing-Long-Duration-Audio.html)

**Comment by atruskie** [comment]
Closed due to inactivity
